#!/bin/bash

if [ ! -d "/proc/$1" ]; then
  echo "Process $1 does not exist"
  exit 1
fi

#Process PPID
PPid=$(grep "PPid" /proc/$1/status | awk '{print $2}')
#process name
name=$(cat /proc/$1/cmdline | tr '\0' ' ')
#process status
status=$(grep "State" /proc/$1/status | awk '{print $2,$3}')
#process memory
mem=$(grep "VmRSS" /proc/$1/status | awk '{print $2,$3}')
#process Open FDs
fds=$(lsof -p $1 | wc -l)
#process Binary inode
inode=$(stat -c "%i" /proc/$1/exe)
#process Binary links
links=$(stat -c "%h" /proc/$1/exe):
#process Cgroup
cgroup=$(cat /proc/$1/cgroup)
#process Namespace PID
ns_pid=$(readlink /proc/$1/ns/pid)
ns_pid=${ns_pid#*[}
ns_pid=${ns_pid%]}
##process NameSpace Network
ns_net=$(readlink /proc/$1/ns/net)
ns_net=${ns_net#*[}
ns_net=${ns_net%]}
##process NameSpace Mount
ns_mnt=$(readlink /proc/$1/ns/mnt)
ns_mnt=${ns_mnt#*[}
ns_mnt=${ns_mnt%]}
#Threads
threads=$(grep "Threads" /proc/41444/status | awk '{print $2}')  



print_row() {
    printf "║ %-12s %-19s ║\n" "$1" "$2"
}

#show () {
#  printf "╔════════════════════════════════════╗\n" 
#  printf "║ %-12s %-19s ║\n" "Process Inspector:" "$1"
#  printf "╠════════════════════════════════════╣\n"
#  printf "║ %-12s %-19s ║\n" "PPid:" "$PPid"
#  printf "║ State: %-28s║\n" "$status" 
#  printf "║ PPid: %-26s║\n" "$PPid"  
#  printf "║ Memory: %-27s║\n" "$mem" 
#  printf "║ Open FDs: %-25s║\n" "$fds" 
#  printf "║                                    ║\n"
#  printf "║ Namespaces:                        ║\n"
#  printf "║ PID: %-30s║\n" "$ns_pid" 
#  printf "║ NET: %-30s║\n" "$ns_net" 
#  printf "║ MNT: %-30s║\n" "$ns_mnt" 
#  printf "║                                    ║\n"
#  printf "║ Cgroup: %-27s║\n" "${cgroup#*::}" 
#  printf "║                                    ║\n"
#  printf "║ Binary inode: %-21s║\n" "$inode" 
#  printf "║ Binary links: %-21s║\n" "$links" 
#  printf "╚════════════════════════════════════╝\n"
#}
show () {
  printf "╔══════════════════════════════════╗\n"
  printf "║ Process Inspector: PID - %-8s║\n" "$1"
  printf "╠══════════════════════════════════╣\n"

  print_row "PPid:" "$PPid"
  print_row "State:" "$status"
  print_row "Memory:" "$mem"
  print_row "Open FDs:" "$fds"
  printf "║                                  ║\n"
  printf "║ Namespaces:                      ║\n"
  print_row "PID:" "$ns_pid"
  print_row "NET:" "$ns_net"
  print_row "MNT:" "$ns_mnt"
  printf "║                                  ║\n" 
  printf "║ Cgroup: %.22s...║\n" "$cgroup"
  printf "║                                  ║\n" 
  print_row "Threads:" "$threads" 
  printf "║                                  ║\n" 
  print_row "Binary-inode" "$inode" 
  print_row "Binary-links" "$links" 
  printf "╚══════════════════════════════════╝\n" 








}


show "$1"

